title: EKS Platform Reference Architecture
description: Reference architecture for EKS-based platform design
url: "https://m-dunbar.github.io"
baseurl: "/eks_platform_reference_architecture"
minimal_mistakes_skin: "air"
breadcrumbs: true

remote_theme: mmistakes/minimal-mistakes

markdown: kramdown

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: single
      toc: true
      toc_sticky: true
      author_profile: false
      sidebar:
        nav: "docs"


exclude:
  - README.md
